name: hello_flutter
description: A simple chat app with Flask backend (v2.3)
publish_to: 'none'

version: 2.3.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  dio: ^5.7.0
  file_picker: ^8.0.3
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  workmanager: ^0.5.1   # ðŸ‘ˆ Ð½ÑƒÐ¶Ð½Ð¾ Ð´Ð»Ñ Ñ„Ð¾Ð½Ð¾Ð²Ð¾Ð¹ Ð¾Ñ‚Ð¿Ñ€Ð°Ð²ÐºÐ¸ ÑÐ¾Ð¾Ð±Ñ‰ÐµÐ½Ð¸Ð¹

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
